#AWS Config
ENV['FOG_PROVIDER']= 'AWS'
ENV['FOG_REGION']= 'eu-west-1'
ENV['FOG_DIRECTORY']= 'davidsrails'
ENV['AWS_ACCESS_KEY_ID']= 'AKIAJ65ARGMI6FM4RMPA'
ENV['AWS_SECRET_ACCESS_KEY']= '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'